[files]
extend-exclude = [
  ".tmp",
  ".typos.toml",
  "Cargo.lock",
]

[default.extend-words]
# If it is a false positive, add the word to the dictionary as follows.
# NotTypoWord = "NotTypoWord"
elete = "elete" # format!("{}elete", "(d)".red().bold())
